webapp/news/models.py
from datetime import datetime
from sqlalchemy.orm import relationship
from webapp.db import db

class News(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String, nullable=False)
    url = db.Column(db.String, unique=True, nullable=False)
    published = db.Column(db.DateTime, nullable=False)
    text = db.Column(db.Text, nullable=True)

    def comments_count(self):
        return Comment.query.filter(Comment.news_id == self.id).count()

    def __repr__(self):
        return 'News {} {}'.format(self.title, self.url)
#Модель News містить поля id (первинний ключ), title (назва новини), url (URL-адреса новини), 
#published (дата публікації) та text (текст новини). Модель Comment містить поля id (первинний ключ), text (текст коментаря), 
#created (дата створення), news_id (зовнішній ключ, що посилається на id новини, 
#до якої відноситься коментар) та user_id (зовнішній ключ, що посилається на id користувача, який залишив коментар)
    
class Comment(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    text = db.Column(db.Text, nullable=False)
    created = db.Column(db.DateTime, nullable=False, default=datetime.now())
    news_id = db.Column(
        db.Integer,
        db.ForeignKey('news.id', ondelete='CASCADE'),
        index=True
    )
    user_id = db.Column(
        db.Integer,
        db.ForeignKey('user.id', ondelete='CASCADE'),
        index=True
    )
    news = relationship('News', backref='comments')
    user = relationship('User', backref='comments')

    def __repr__(self):
        return '<Comment {}>'.format(self.id)
#модель Comment містить відношення news і user, 
#які посилаються на відповідні об'єкти моделі News і User, використовуючи зовнішні ключі.
    

webapp/news/forms.py
from flask_wtf import FlaskForm
from wtforms import HiddenField, StringField, SubmitField
from wtforms.validators import DataRequired, ValidationError

from webapp.news.models import News

class CommentForm(FlaskForm):
    news_id = HiddenField('News ID', validators=[DataRequired()])
    comment_text = StringField("Your comment:", validators=[DataRequired()], render_kw={"class": "form-control"})
    submit = SubmitField('Send comment', render_kw={"class": "btn btn-primary"})

    def validate_news_id(self, news_id):
        if not News.query.get(news_id.data):
            raise ValidationError('Article with this ID doesnt exist')
#Клас CommentForm описує форму для додавання коментаря до новини. Він успадковує клас FlaskForm.
#news_id - приховане поле з ID новини, до якої додається коментар.
#comment_text - текстове поле для введення коментаря.
#submit - кнопка для відправки форми.
#Метод validate_news_id виконує перевірку наявності новини з вказаним ID в базі даних. 
#Якщо новина не знайдена, викликається помилка валідації з повідомленням "Article with this ID doesnt exist".

webapp/news/views.py
from flask import abort, Blueprint, current_app, flash, render_template, redirect, request, url_for
from flask_login import current_user, login_required

from webapp.db import db
from webapp.news.forms import CommentForm
from webapp.news.models import Comment, News
from webapp.weather import weather_by_city
from webapp.utils import get_redirect_target

blueprint = Blueprint('news', __name__)

@blueprint.route('/')
def index():
    title = "Weather/News report"
    weather = weather_by_city(current_app.config['WEATHER_DEFAULT_CITY'])
    news_list = News.query.filter(News.text.isnot(None)).order_by(News.published.desc()).all()
    return render_template('news/index.html', page_title=title, weather=weather, news_list=news_list)
#функція index() є однією з маршрутів веб-додатка, який обробляє запит до головної сторінки. 
#Функція відображає погоду за замовчуванням та список новин, відсортованих за датою публікації.

@blueprint.route('/news/<int:news_id>')
def single_news(news_id):
    my_news = News.query.filter(News.id == news_id).first()

    if not my_news:
        abort(404)
    comment_form = CommentForm(news_id=my_news.id)
    return render_template('news/single_news.html', page_title=my_news.title, news=my_news, comment_form=comment_form)
#функція single_news(news_id) також є маршрутом веб-додатка і відображає сторінку новини за заданим news_id. 
#Крім того, вона створює форму коментарів, яка передається у шаблон сторінки.

@blueprint.route('/news/comment', methods=['POST'])
@login_required
def add_comment():
    form = CommentForm()
    if form.validate_on_submit():
            comment = Comment(text=form.comment_text.data, news_id=form.news_id.data, user_id=current_user.id)
            db.session.add(comment)
            db.session.commit()
            flash('Succefully added')
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash('Mistake in field {} {}'.format(
                    getattr(form, field).label.text,
                    error
                ))
    return redirect(get_redirect_target())
#функція add_comment() є маршрутом веб-додатка для додавання коментарів до новин. 
#Функція перевіряє, чи форма коментарів валідна та додає коментар до бази даних. 
#В іншому випадку вона відображає повідомлення про помилки на сторінку.

webapp/templates/news/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ page_title }}</h1>
    <div class="row">
        <div class ="col-8">
            {% include('messages.html') %}
            <h2>News</h2>
            {% for news in news_list %}
            <h3><a href="{{ url_for('news.single_news', news_id=news.id) }}">{{ news.title }}</a></h3>
            <p>{{ news.published.strftime('%d.%m.%Y') }} | Comments: {{ news.comments_count() }}</p>
            <hr />
            {% endfor %}
            
        </div>
        <div class="col-4">
            <h2>Current weather in Lviv,Ukraine</h2>
            {% if weather %}
                <p>Temperature: {{ weather.temp_C }}, feels like {{ weather.FeelsLikeC }}</p>
                <p>Weather description : {{ weather.weatherDesc[0]['value'] }}</p>
            {% else %}
                Weather forecast temporarly unavailible
            {% endif %}
        </div>
    </div>    
    {% endblock %}

webapp/templates/news/single_news.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class =" news-content">
            {% include('messages.html') %}
            {{ news.text|safe }}
            {% if news.comments %}
                <h3>Comments:</h3>
                {% for comment in news.comments %}
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                    <p class="card-text">{{ comment.text }}</p>
                    <p class="card-text">Published: {{ comment.created.strftime('%d.%m.%Y') }} ||
                        User: {{ comment.user.username }}</p>
                    </div>
                </div>
                {% endfor %}
            {% endif %}
            {% if current_user.is_authenticated %}
                <form action="{{ url_for('news.add_comment') }}" method="POST" class="comm">
                    {{ comment_form.hidden_tag() }}
                    <div class="form-group">
                        {{ comment_form.comment_text.label }}
                        {{ comment_form.comment_text() }}
                    </div>
                    <div class="form-group">
                    {{ comment_form.submit() }}
                    </div>
                </form>
            {% else %}
                <p>
                    <a href="{{ url_for('user.login', next=request.full_path) }}">Sign up</a> to send comments
                </p>
            {% endif %}
        </div>
        
    </div>    
    {% endblock %}