webapp/user/models.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

from webapp.db import db

class User(db.Model, UserMixin): 
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(48), index=True, unique=True)
    password = db.Column(db.String(128))
    role = db.Column(db.String(10), index=True)
    email = db.Column(db.String(50),index=True, unique=True)

    def set_password(self, password):
        self.password = generate_password_hash(password)
    
    def check_password(self, password):
        return check_password_hash(self.password, password)

    @property
    def is_admin(self):
        return self.role == 'admin'

    def __repr__(self):
        return '<User {}>'.format(self.username)
    
#Клас User наслідується від db.Model і UserMixin. 
# Він містить поля id, username, password, role та email. 
# Метод set_password() встановлює хеш-значення пароля користувача, 
# метод check_password() перевіряє відповідність введеного пароля збереженому хеш-значенню пароля. 
# Властивість is_admin повертає True, якщо користувач має роль адміністратора. Метод __repr__() повертає рядок з ім'ям користувача.

webapp/user/forms.py
from flask_wtf import FlaskForm
from wtforms import BooleanField, StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo, ValidationError

from webapp.user.models import User

class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()], render_kw={"class": "form-control"})
    password = PasswordField('Password', validators=[DataRequired()], render_kw={"class": "form-control"})
    remember_me = BooleanField('Remember me', default=True, render_kw={"class": "form-check-input"})
    submit = SubmitField('Submit', render_kw={'class': "btn btn-primary"})



class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()], render_kw={"class": "form-control"})
    email = StringField('User email', validators=[DataRequired(), Email()], render_kw={"class": "form-control"})
    password2 = PasswordField('Repeat password', validators=[DataRequired(), EqualTo('password')], render_kw={"class": "form-control"})
    password = PasswordField('Enter password', validators=[DataRequired()], render_kw={"class": "form-control"})
    submit = SubmitField('Submit', render_kw={'class': "btn btn-primary"})
    
    def validate_username(self, username):
        user_count = User.query.filter_by(username=username.data).count()
        if user_count > 0:
            raise ValidationError('User with this username already exists')
        
    def validate_email(self, email):
        user_count = User.query.filter_by(email=email.data).count()
        if user_count > 0:
            raise ValidationError('User with this email already exists')

#Kод містить два класи форм, що використовуються для створення форм для входу і реєстрації користувачів. 
# Клас LoginForm містить поля для введення імені користувача, пароля та прапорця для запам'ятовування користувача. 
# Клас RegistrationForm містить поля для введення імені користувача, електронної пошти та пароля, 
# який користувач повинен ввести двічі для перевірки правильності. 
# В класі RegistrationForm також є дві функції для перевірки унікальності імені користувача та електронної пошти. 
# Якщо користувач з таким ім'ям користувача або електронною поштою вже існує, функції викидають помилку валідації з відповідним повідомленням.
    

webapp/user/views.py
from webapp.user.forms import LoginForm, RegistrationForm
from webapp.user.models import User
from webapp.db import db

from flask import Blueprint, flash, redirect, url_for, render_template
from flask_login import current_user, login_user, logout_user
from webapp.utils import get_redirect_target

blueprint= Blueprint('user', __name__, url_prefix='/users')

@blueprint.route('/login')
def login():
    if current_user.is_authenticated:
        return redirect(get_redirect_target())
    title = 'Authorization'
    login_form = LoginForm()
    return render_template('user/login.html', page_title = title, form = login_form)

@blueprint.route('/process-login', methods=['POST'])
def process_login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter(User.username == form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            flash("You are logged in")
            return redirect(url_for('news.index'))
      
    flash('Mistake in username or password')
    return redirect(url_for('user.login'))

@blueprint.route('/logout')
def logout():
    logout_user()
    flash('Logged out')
    return redirect(url_for('news.index'))

@blueprint.route('/register')
def register():
    if current_user.is_authenticated:
        return redirect(url_for('news.index'))
    title = 'Registration'
    form = RegistrationForm()
    return render_template('user/registration.html', page_title = title, form = form)

@blueprint.route('/process-reg', methods=['POST'])
def process_reg():
    form = RegistrationForm()
    if form.validate_on_submit():
        news_user = User(username=form.username.data, email=form.email.data, role='user')
        news_user.set_password(form.password.data)
        db.session.add(news_user)
        db.session.commit()
        flash('You are passed a registration')
        return redirect(url_for('user.login'))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash('Problem in {} : {}'.format(
                    getattr(form,field).label.text,
                    error
                ))
        flash('Please correct the errors in the form')
        return redirect(url_for('user.register'))

#код для Flask-блупрінту, який обробляє сторінки веб-додатку пов'язані з аутентифікацією та реєстрацією користувачів.
#Перші дві функції - це сторінки для входу користувача. 
# Функція login показує сторінку входу, а функція process_login перевіряє, чи вірні введені ім'я користувача та пароль. 
# Якщо вони вірні, вона залогінює користувача та перенаправить його на сторінку з новинами. 
# В іншому випадку вона поверне його на сторінку входу з помилкою.
#Функція logout від'єднує користувача від системи та перенаправляє його на головну сторінку з повідомленням про вихід.
#Функції register та process_reg відповідають за реєстрацію користувача. Функція register показує сторінку реєстрації, 
# а функція process_reg перевіряє правильність введених даних та додає нового користувача в базу даних, 
# якщо вони вірні. Якщо ж дані не вірні, 
# вона повертає користувача на сторінку реєстрації з відповідною помилкою.
#В цьому коді також використовується шаблонизатор Jinja2 для рендерингу HTML-сторінок.

webapp/templates/user/login.html
{% extends 'base.html' %}

{% block content %}
        <h1><div class="mx-auto p-2" style="width: 300px;">{{ page_title }}</div></h1>
        <div class="row">
            <div class="mx-auto p-2" style="width: 300px;">
                {% include('messages.html') %}   
                <form action="{{ url_for('user.process_login') }}" method="POST">
                    {{ form.hidden_tag() }}
                    <div class="mb-3">
                        {{ form.username.label }}
                        {{ form.username() }}
                    </div>
                    <div class="mb-3">
                        {{ form.password.label }}
                        {{ form.password() }}
                    </div>
                    <div class="form-group form-check">
                        {{ form.remember_me() }}
                        {{ form.remember_me.label(class_='form-check-label') }}
                    </div>
                    {{ form.submit() }}
                </form>
            </div>
{% endblock %}

webapp/templates/user/registration.html
{% extends 'base.html' %}

{% block content %}
        <h1><div class="mx-auto p-2" style="width: 300px;">{{ page_title }}</div></h1>
        {% include('messages.html') %} 
        <div class="row" >
            <div class="mx-auto p-2" style="width: 300px;">  
                <form action="{{ url_for('user.process_reg') }}" method="POST">
                    {{ form.hidden_tag() }}
                    <div class="mb-3">
                        {{ form.username.label }}
                        {{ form.username() }}
                    </div>
                    <div class="mb-3">
                        {{ form.email.label }}
                        {{ form.email() }}
                    </div>
                    <div class="mb-3">
                        {{ form.password.label }}
                        {{ form.password() }}
                    </div>
                    <div class="mb-3">
                        {{ form.password2.label }}
                        {{ form.password2() }}
                    </div>
                    {{ form.submit() }}
                </form>
            </div>
{% endblock %}