webapp/admin/views.py
from flask import Blueprint, render_template
from webapp.user.decorators import admin_required


blueprint = Blueprint('admin', __name__, url_prefix='/admin')

@blueprint.route('/')
@admin_required
def admin_index():
        title = "Control panel"
        return render_template('admin/index.html', page_title=title)
#Kод створює маршрут "/admin/", який веде до сторінки "Control panel", і доступний лише для користувачів з правами адміністратора, 
#які авторизовані в системі. Для перевірки доступності використовується декоратор @admin_required. 
#Якщо користувач не авторизований або не має прав адміністратора, 
#він буде перенаправлений на сторінку авторизації або на головну сторінку (залежно від налаштувань системи).

webapp/user/views.py
from webapp.user.forms import LoginForm, RegistrationForm
from webapp.user.models import User
from webapp.db import db

from flask import Blueprint, flash, redirect, url_for, render_template
from flask_login import current_user, login_user, logout_user
from webapp.utils import get_redirect_target

blueprint= Blueprint('user', __name__, url_prefix='/users')

@blueprint.route('/login')
def login():
    if current_user.is_authenticated:
        return redirect(get_redirect_target())
    title = 'Authorization'
    login_form = LoginForm()
    return render_template('user/login.html', page_title = title, form = login_form)

@blueprint.route('/process-login', methods=['POST'])
def process_login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter(User.username == form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            flash("You are logged in")
            return redirect(url_for('news.index'))
      
    flash('Mistake in username or password')
    return redirect(url_for('user.login'))

@blueprint.route('/logout')
def logout():
    logout_user()
    flash('Logged out')
    return redirect(url_for('news.index'))

@blueprint.route('/register')
def register():
    if current_user.is_authenticated:
        return redirect(url_for('news.index'))
    title = 'Registration'
    form = RegistrationForm()
    return render_template('user/registration.html', page_title = title, form = form)

@blueprint.route('/process-reg', methods=['POST'])
def process_reg():
    form = RegistrationForm()
    if form.validate_on_submit():
        news_user = User(username=form.username.data, email=form.email.data, role='user')
        news_user.set_password(form.password.data)
        db.session.add(news_user)
        db.session.commit()
        flash('You are passed a registration')
        return redirect(url_for('user.login'))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash('Problem in {} : {}'.format(
                    getattr(form,field).label.text,
                    error
                ))
        flash('Please correct the errors in the form')
        return redirect(url_for('user.register'))

#код для Flask-блупрінту, який обробляє сторінки веб-додатку пов'язані з аутентифікацією та реєстрацією користувачів.
#Перші дві функції - це сторінки для входу користувача. 
# Функція login показує сторінку входу, а функція process_login перевіряє, чи вірні введені ім'я користувача та пароль. 
# Якщо вони вірні, вона залогінює користувача та перенаправить його на сторінку з новинами. 
# В іншому випадку вона поверне його на сторінку входу з помилкою.
#Функція logout від'єднує користувача від системи та перенаправляє його на головну сторінку з повідомленням про вихід.
#Функції register та process_reg відповідають за реєстрацію користувача. Функція register показує сторінку реєстрації, 
# а функція process_reg перевіряє правильність введених даних та додає нового користувача в базу даних, 
# якщо вони вірні. Якщо ж дані не вірні, 
# вона повертає користувача на сторінку реєстрації з відповідною помилкою.
#В цьому коді також використовується шаблонизатор Jinja2 для рендерингу HTML-сторінок.

webapp/templates/base.html
<!doctype html>
<html lang="en">
  <head>
  
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.rtl.min.css" integrity="sha384-T5m5WERuXcjgzF8DAb7tRkByEZQGcpraRTinjpywg37AO96WoYN9+hrhDVoM6CaT" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename='style.css')}}">
    <title>{{ page_title }}</title>
  </head>
  <body data-bs-theme="dark">
    {% include 'menu.html' %}
    <div class = "container">
        {% block content %}{% endblock %}
       
    </div>
    <footer class="bg-dark text-center text-lg-start py-2">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
        <h6 class="text-uppercase">About</h6>
        <p>The goal of this project is to develop a web application using Python and JavaScript.</p>
      </div>
      <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
        <h6 class="text-uppercase">Contact</h6>
        <ul class="list-unstyled mb-0">
          <li><a href="mailto:kyrylo.bezsonov@lnu.edu.ua">kyrylo.bezsonov@lnu.edu.ua</a></li>
        </ul>
      </div>
      <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
        <h6 class="text-uppercase">GitHub</h6>
        <ul class="list-unstyled mb-0">
          <li><a href="https://github.com/killreal2002/diplom">https://github.com/killreal2002/diplom</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="text-center p-2 text-muted">
    Made by Kyrylo Bezsonov
  </div>
</footer>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <!-- 
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    -->
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js" integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>
    
  </body>
</html>

webapp/templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.rtl.min.css" integrity="sha384-T5m5WERuXcjgzF8DAb7tRkByEZQGcpraRTinjpywg37AO96WoYN9+hrhDVoM6CaT" crossorigin="anonymous">

    <title>{{ page_title }}</title>
  </head>
  <body>
    <div class = "container">
    <h1>{{ page_title }}</h1>
    <div class="row">
        <div class ="col-8">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                <div class="alert alert-warning" role="alert">
                    {% for message in messages %}
                        {{ message }}<br>
                    {% endfor %}
                </div>
                {% endif %}
            {% endwith %}             
            <h2>News</h2>
            {% for news in news_list %}
            <h3><a href="{{ news.url }}">{{ news.title }}</a></h3>
            <p>{{ news.published.strftime('%d.%m.%Y') }}</p>
            <hr />
            {% endfor %}
            
        </div>
        <div class="col-4">
            <h2>Weather report</h2>
            {% if weather %}
                Temperature: {{ weather.temp_C }}, feels like {{ weather.FeelsLikeC }}
            {% else %}
                Weather forecast temporarly unavailible
            {% endif %}
        </div>
    </div>    
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <!-- 
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    -->
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js" integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js" integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ" crossorigin="anonymous"></script>
    
  </body>
</html>

webapp/templates/menu.html
<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">Python News</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Homepage</a>
          </li>
          {% if current_user.is_authenticated %}
          <li class="nav-item">
            <span class="nav-link">Hello {{ current_user.username }}</span>
          </li>
          {% if current_user.is_admin %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('admin.admin_index') }}">Admin panel</a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('user.logout') }}">Logout</a>
          </li>
            {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('user.login') }}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('user.register') }}">Registration</a>
          </li>
            {% endif %}
          

        </ul>
      </div>
    </div>
  </nav>

webapp/templates/messages.html
{% with messages = get_flashed_messages() %}
    {% if messages %}
    <div class="alert alert-warning" role="alert">
        {% for message in messages %}
            {{ message }}<br>
        {% endfor %}
    </div>
    {% endif %}
{% endwith %} 